from __future__ import annotations

from typing import Final

from pyanilist._aclient import AsyncAniList
from pyanilist._client import AniList
from pyanilist._enums import (
    CharacterRole,
    CharacterSort,
    ExternalLinkType,
    MediaFormat,
    MediaRankType,
    MediaRelation,
    MediaSeason,
    MediaSort,
    MediaSource,
    MediaStatus,
    MediaType,
    RecommendationSort,
    StaffSort,
    StudioSort,
)
from pyanilist._errors import AnilistError, InvalidMediaQueryError, MediaNotFoundError, RateLimitError
from pyanilist._types import (
    AiringSchedule,
    Character,
    CharacterImage,
    CharacterName,
    FuzzyDate,
    Media,
    MediaCoverImage,
    MediaExternalLink,
    MediaQueryKwargs,
    MediaRank,
    MediaStreamingEpisode,
    MediaTag,
    MediaTitle,
    MediaTrailer,
    RecommendedMedia,
    RelatedMedia,
    Staff,
    StaffImage,
    StaffName,
    Studio,
    YearsActive,
)
from pyanilist._version import __version__

__all__: Final = (
    "AiringSchedule",
    "AniList",
    "AnilistError",
    "AsyncAniList",
    "Character",
    "CharacterImage",
    "CharacterName",
    "CharacterRole",
    "CharacterSort",
    "ExternalLinkType",
    "FuzzyDate",
    "InvalidMediaQueryError",
    "Media",
    "MediaCoverImage",
    "MediaExternalLink",
    "MediaFormat",
    "MediaNotFoundError",
    "MediaQueryKwargs",
    "MediaRank",
    "MediaRankType",
    "MediaRelation",
    "MediaSeason",
    "MediaSort",
    "MediaSource",
    "MediaStatus",
    "MediaStreamingEpisode",
    "MediaTag",
    "MediaTitle",
    "MediaTrailer",
    "MediaType",
    "NoMediaArgumentsError",
    "RateLimitError",
    "RecommendationSort",
    "RecommendedMedia",
    "RelatedMedia",
    "Staff",
    "StaffImage",
    "StaffName",
    "StaffSort",
    "Studio",
    "StudioSort",
    "YearsActive",
    "__version__",
)
